"""
Tutorial: Understanding Embeddings

Embeddings convert text into numerical vectors that capture semantic meaning.
Similar texts have similar vectors, enabling semantic search.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from utils.claude_helper import get_client


def get_embedding(text, model="voyage-3"):
    """
    Get embedding vector for text using Anthropic's embedding model

    Note: As of now, you'll need to use a separate embedding service like:
    - OpenAI embeddings
    - Voyage AI
    - Cohere
    - Or local models like sentence-transformers

    This example shows the concept.
    """
    # For this tutorial, we'll demonstrate the concept
    # In practice, you'd use:
    # from openai import OpenAI
    # client = OpenAI()
    # response = client.embeddings.create(input=text, model="text-embedding-3-small")
    # return response.data[0].embedding

    print(f"Getting embedding for: '{text[:50]}...'")
    print("(Using mock embeddings for demo)")

    # Mock embedding (in reality, this would be a ~1536 dimension vector)
    import hashlib

    # Create a deterministic but fake embedding based on text hash
    hash_val = int(hashlib.md5(text.encode()).hexdigest(), 16)
    mock_embedding = [(hash_val + i) % 100 / 100.0 for i in range(8)]

    return mock_embedding


def cosine_similarity(vec1, vec2):
    """Calculate cosine similarity between two vectors"""
    import math

    dot_product = sum(a * b for a, b in zip(vec1, vec2))
    magnitude1 = math.sqrt(sum(a * a for a in vec1))
    magnitude2 = math.sqrt(sum(b * b for b in vec2))

    return dot_product / (magnitude1 * magnitude2)


def demo_embeddings():
    """Demonstrate how embeddings work"""

    print("=" * 80)
    print("UNDERSTANDING EMBEDDINGS")
    print("=" * 80)

    # Example texts
    texts = {
        "dog1": "The dog is playing in the park",
        "dog2": "A puppy is running outside",
        "cat": "The cat is sleeping on the couch",
        "car": "The car is parked in the garage",
        "code": "Python is a programming language"
    }

    print("\nSample Texts:")
    print("-" * 80)
    for key, text in texts.items():
        print(f"{key}: {text}")

    # Get embeddings
    print("\n" + "=" * 80)
    print("GETTING EMBEDDINGS")
    print("=" * 80)
    embeddings = {}
    for key, text in texts.items():
        embeddings[key] = get_embedding(text)
        print(f"{key}: [{', '.join(f'{x:.3f}' for x in embeddings[key][:4])}...]")

    # Calculate similarities
    print("\n" + "=" * 80)
    print("SIMILARITY SCORES (Cosine Similarity)")
    print("=" * 80)

    comparisons = [
        ("dog1", "dog2", "Similar topic (dogs)"),
        ("dog1", "cat", "Related topic (pets)"),
        ("dog1", "car", "Unrelated topic"),
        ("dog1", "code", "Completely different"),
    ]

    for key1, key2, description in comparisons:
        similarity = cosine_similarity(embeddings[key1], embeddings[key2])
        print(f"{key1} vs {key2}: {similarity:.3f} - {description}")

    # Explain
    print("\n" + "=" * 80)
    print("KEY CONCEPTS")
    print("=" * 80)
    print("""
1. WHAT ARE EMBEDDINGS?
   - Vectors (lists of numbers) that represent text meaning
   - Typically 768-1536 dimensions (we show 8 for demo)
   - Generated by neural networks trained on massive text data

2. WHY ARE THEY USEFUL?
   - Capture semantic meaning, not just keywords
   - Enable similarity search
   - "dog" and "puppy" have similar embeddings
   - "dog" and "car" have different embeddings

3. COSINE SIMILARITY
   - Measures how similar two vectors are
   - Range: -1 (opposite) to 1 (identical)
   - Typically: >0.8 very similar, 0.5-0.8 related, <0.5 different

4. PRACTICAL USE
   - Store document embeddings in vector database
   - Convert user query to embedding
   - Find documents with similar embeddings
   - Return most relevant documents

5. EMBEDDING PROVIDERS
   - OpenAI: text-embedding-3-small (cheap, good)
   - Voyage AI: voyage-3 (optimized for retrieval)
   - Cohere: embed-english-v3.0
   - Local: sentence-transformers (free, runs locally)
    """)

    print("\n" + "=" * 80)
    print("NEXT STEP: Set up vector database (ChromaDB)")
    print("=" * 80)


if __name__ == "__main__":
    demo_embeddings()
